export const COUNTRIES = [
  { name: "India", iso2: "IN", phoneCode: "+91" },
  { name: "United Arab Emirates", iso2: "AE", phoneCode: "+971" },
  { name: "United States", iso2: "US", phoneCode: "+1" },
  { name: "United Kingdom", iso2: "GB", phoneCode: "+44" },
  { name: "Germany", iso2: "DE", phoneCode: "+49" },
  { name: "Belgium", iso2: "BE", phoneCode: "+32" },
  { name: "Hong Kong", iso2: "HK", phoneCode: "+852" },
  { name: "Thailand", iso2: "TH", phoneCode: "+66" },
  { name: "Singapore", iso2: "SG", phoneCode: "+65" },
  { name: "China", iso2: "CN", phoneCode: "+86" },
  { name: "Japan", iso2: "JP", phoneCode: "+81" },
  { name: "Australia", iso2: "AU", phoneCode: "+61" },
  { name: "Canada", iso2: "CA", phoneCode: "+1" },
  { name: "France", iso2: "FR", phoneCode: "+33" },
  { name: "Italy", iso2: "IT", phoneCode: "+39" },
  { name: "Spain", iso2: "ES", phoneCode: "+34" },
  { name: "Switzerland", iso2: "CH", phoneCode: "+41" },
  { name: "Israel", iso2: "IL", phoneCode: "+972" },
  { name: "South Africa", iso2: "ZA", phoneCode: "+27" },
  { name: "Turkey", iso2: "TR", phoneCode: "+90" },
];

export const STATES = [
  { countryIso2: "IN", code: "AN", name: "Andaman and Nicobar Islands" },
  { countryIso2: "IN", code: "AP", name: "Andhra Pradesh" },
  { countryIso2: "IN", code: "AR", name: "Arunachal Pradesh" },
  { countryIso2: "IN", code: "AS", name: "Assam" },
  { countryIso2: "IN", code: "BR", name: "Bihar" },
  { countryIso2: "IN", code: "CH", name: "Chandigarh" },
  { countryIso2: "IN", code: "CT", name: "Chhattisgarh" },
  { countryIso2: "IN", code: "DH", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { countryIso2: "IN", code: "DL", name: "Delhi" },
  { countryIso2: "IN", code: "GA", name: "Goa" },
  { countryIso2: "IN", code: "GJ", name: "Gujarat" },
  { countryIso2: "IN", code: "HR", name: "Haryana" },
  { countryIso2: "IN", code: "HP", name: "Himachal Pradesh" },
  { countryIso2: "IN", code: "JK", name: "Jammu and Kashmir" },
  { countryIso2: "IN", code: "JH", name: "Jharkhand" },
  { countryIso2: "IN", code: "KA", name: "Karnataka" },
  { countryIso2: "IN", code: "KL", name: "Kerala" },
  { countryIso2: "IN", code: "LA", name: "Ladakh" },
  { countryIso2: "IN", code: "LD", name: "Lakshadweep" },
  { countryIso2: "IN", code: "MP", name: "Madhya Pradesh" },
  { countryIso2: "IN", code: "MH", name: "Maharashtra" },
  { countryIso2: "IN", code: "MN", name: "Manipur" },
  { countryIso2: "IN", code: "ML", name: "Meghalaya" },
  { countryIso2: "IN", code: "MZ", name: "Mizoram" },
  { countryIso2: "IN", code: "NL", name: "Nagaland" },
  { countryIso2: "IN", code: "OR", name: "Odisha" },
  { countryIso2: "IN", code: "PY", name: "Puducherry" },
  { countryIso2: "IN", code: "PB", name: "Punjab" },
  { countryIso2: "IN", code: "RJ", name: "Rajasthan" },
  { countryIso2: "IN", code: "SK", name: "Sikkim" },
  { countryIso2: "IN", code: "TN", name: "Tamil Nadu" },
  { countryIso2: "IN", code: "TG", name: "Telangana" },
  { countryIso2: "IN", code: "TR", name: "Tripura" },
  { countryIso2: "IN", code: "UP", name: "Uttar Pradesh" },
  { countryIso2: "IN", code: "UT", name: "Uttarakhand" },
  { countryIso2: "IN", code: "WB", name: "West Bengal" },
  { countryIso2: "AE", code: "AZ", name: "Abu Dhabi" },
  { countryIso2: "AE", code: "AJ", name: "Ajman" },
  { countryIso2: "AE", code: "DU", name: "Dubai" },
  { countryIso2: "AE", code: "FU", name: "Fujairah" },
  { countryIso2: "AE", code: "RK", name: "Ras Al Khaimah" },
  { countryIso2: "AE", code: "SH", name: "Sharjah" },
  { countryIso2: "AE", code: "UQ", name: "Umm Al Quwain" },
  { countryIso2: "US", code: "CA", name: "California" },
  { countryIso2: "US", code: "NY", name: "New York" },
  { countryIso2: "GB", code: "ENG", name: "England" },
  { countryIso2: "GB", code: "SCT", name: "Scotland" },
  { countryIso2: "DE", code: "BE", name: "Berlin" },
  { countryIso2: "DE", code: "BY", name: "Bavaria" },
];

export const CITIES = [
  { countryIso2: "IN", stateCode: "MH", name: "Mumbai" },
  { countryIso2: "IN", stateCode: "MH", name: "Pune" },
  { countryIso2: "IN", stateCode: "GJ", name: "Ahmedabad" },
  { countryIso2: "IN", stateCode: "GJ", name: "Surat" },
  { countryIso2: "IN", stateCode: "DL", name: "New Delhi" },
  { countryIso2: "IN", stateCode: "RJ", name: "Jaipur" },
  { countryIso2: "AE", stateCode: "DU", name: "Dubai" },
  { countryIso2: "AE", stateCode: "AZ", name: "Abu Dhabi" },
  { countryIso2: "AE", stateCode: "SH", name: "Sharjah" },
  { countryIso2: "US", stateCode: "CA", name: "Los Angeles" },
  { countryIso2: "US", stateCode: "CA", name: "San Francisco" },
  { countryIso2: "US", stateCode: "NY", name: "New York City" },
  { countryIso2: "GB", stateCode: "ENG", name: "London" },
  { countryIso2: "GB", stateCode: "ENG", name: "Manchester" },
  { countryIso2: "GB", stateCode: "SCT", name: "Edinburgh" },
  { countryIso2: "DE", stateCode: "BE", name: "Berlin" },
  { countryIso2: "DE", stateCode: "BY", name: "Munich" },
];
