export const COUNTRIES = [
  { name: "India", iso2: "IND", phoneCode: "+91" },
  { name: "United Arab Emirates", iso2: "ARE", phoneCode: "+971" },
  { name: "United States", iso2: "USA", phoneCode: "+1" },
  { name: "United Kingdom", iso2: "GBR", phoneCode: "+44" },
  { name: "Germany", iso2: "DEU", phoneCode: "+49" },
  { name: "Belgium", iso2: "BEL", phoneCode: "+32" },
  { name: "Hong Kong", iso2: "HKG", phoneCode: "+852" },
  { name: "Thailand", iso2: "THA", phoneCode: "+66" },
  { name: "Singapore", iso2: "SGP", phoneCode: "+65" },
  { name: "China", iso2: "CHN", phoneCode: "+86" },
  { name: "Japan", iso2: "JPN", phoneCode: "+81" },
  { name: "Australia", iso2: "AUS", phoneCode: "+61" },
  { name: "Canada", iso2: "CAN", phoneCode: "+1" },
  { name: "France", iso2: "FRA", phoneCode: "+33" },
  { name: "Italy", iso2: "ITA", phoneCode: "+39" },
  { name: "Spain", iso2: "ESP", phoneCode: "+34" },
  { name: "Switzerland", iso2: "CHE", phoneCode: "+41" },
  { name: "Israel", iso2: "ISR", phoneCode: "+972" },
  { name: "South Africa", iso2: "ZAF", phoneCode: "+27" },
  { name: "Turkey", iso2: "TUR", phoneCode: "+90" },
];

const LEGACY_COUNTRY_CODES = {
  IN: "IND",
  AE: "ARE",
  US: "USA",
  GB: "GBR",
  UK: "GBR",
  DE: "DEU",
  BE: "BEL",
  HK: "HKG",
  TH: "THA",
  SG: "SGP",
  CN: "CHN",
  JP: "JPN",
  AU: "AUS",
  CA: "CAN",
  FR: "FRA",
  IT: "ITA",
  ES: "ESP",
  CH: "CHE",
  IL: "ISR",
  ZA: "ZAF",
  TR: "TUR",
};

export const normalizeCountryCode = (value) => {
  const code = String(value ?? "").trim().toUpperCase();
  return LEGACY_COUNTRY_CODES[code] ?? code;
};

export const STATES = [
  { countryIso2: "IND", code: "AN", name: "Andaman and Nicobar Islands" },
  { countryIso2: "IND", code: "AP", name: "Andhra Pradesh" },
  { countryIso2: "IND", code: "AR", name: "Arunachal Pradesh" },
  { countryIso2: "IND", code: "AS", name: "Assam" },
  { countryIso2: "IND", code: "BR", name: "Bihar" },
  { countryIso2: "IND", code: "CH", name: "Chandigarh" },
  { countryIso2: "IND", code: "CT", name: "Chhattisgarh" },
  { countryIso2: "IND", code: "DH", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { countryIso2: "IND", code: "DL", name: "Delhi" },
  { countryIso2: "IND", code: "GA", name: "Goa" },
  { countryIso2: "IND", code: "GJ", name: "Gujarat" },
  { countryIso2: "IND", code: "HR", name: "Haryana" },
  { countryIso2: "IND", code: "HP", name: "Himachal Pradesh" },
  { countryIso2: "IND", code: "JK", name: "Jammu and Kashmir" },
  { countryIso2: "IND", code: "JH", name: "Jharkhand" },
  { countryIso2: "IND", code: "KA", name: "Karnataka" },
  { countryIso2: "IND", code: "KL", name: "Kerala" },
  { countryIso2: "IND", code: "LA", name: "Ladakh" },
  { countryIso2: "IND", code: "LD", name: "Lakshadweep" },
  { countryIso2: "IND", code: "MP", name: "Madhya Pradesh" },
  { countryIso2: "IND", code: "MH", name: "Maharashtra" },
  { countryIso2: "IND", code: "MN", name: "Manipur" },
  { countryIso2: "IND", code: "ML", name: "Meghalaya" },
  { countryIso2: "IND", code: "MZ", name: "Mizoram" },
  { countryIso2: "IND", code: "NL", name: "Nagaland" },
  { countryIso2: "IND", code: "OR", name: "Odisha" },
  { countryIso2: "IND", code: "PY", name: "Puducherry" },
  { countryIso2: "IND", code: "PB", name: "Punjab" },
  { countryIso2: "IND", code: "RJ", name: "Rajasthan" },
  { countryIso2: "IND", code: "SK", name: "Sikkim" },
  { countryIso2: "IND", code: "TN", name: "Tamil Nadu" },
  { countryIso2: "IND", code: "TG", name: "Telangana" },
  { countryIso2: "IND", code: "TR", name: "Tripura" },
  { countryIso2: "IND", code: "UP", name: "Uttar Pradesh" },
  { countryIso2: "IND", code: "UT", name: "Uttarakhand" },
  { countryIso2: "IND", code: "WB", name: "West Bengal" },
  { countryIso2: "ARE", code: "AZ", name: "Abu Dhabi" },
  { countryIso2: "ARE", code: "AJ", name: "Ajman" },
  { countryIso2: "ARE", code: "DU", name: "Dubai" },
  { countryIso2: "ARE", code: "FU", name: "Fujairah" },
  { countryIso2: "ARE", code: "RK", name: "Ras Al Khaimah" },
  { countryIso2: "ARE", code: "SH", name: "Sharjah" },
  { countryIso2: "ARE", code: "UQ", name: "Umm Al Quwain" },
  { countryIso2: "USA", code: "CA", name: "California" },
  { countryIso2: "USA", code: "NY", name: "New York" },
  { countryIso2: "GBR", code: "ENG", name: "England" },
  { countryIso2: "GBR", code: "SCT", name: "Scotland" },
  { countryIso2: "DEU", code: "BE", name: "Berlin" },
  { countryIso2: "DEU", code: "BY", name: "Bavaria" },
];

export const CITIES = [
  { countryIso2: "IND", stateCode: "MH", name: "Mumbai" },
  { countryIso2: "IND", stateCode: "MH", name: "Pune" },
  { countryIso2: "IND", stateCode: "GJ", name: "Ahmedabad" },
  { countryIso2: "IND", stateCode: "GJ", name: "Surat" },
  { countryIso2: "IND", stateCode: "DL", name: "New Delhi" },
  { countryIso2: "IND", stateCode: "RJ", name: "Jaipur" },
  { countryIso2: "ARE", stateCode: "DU", name: "Dubai" },
  { countryIso2: "ARE", stateCode: "AZ", name: "Abu Dhabi" },
  { countryIso2: "ARE", stateCode: "SH", name: "Sharjah" },
  { countryIso2: "USA", stateCode: "CA", name: "Los Angeles" },
  { countryIso2: "USA", stateCode: "CA", name: "San Francisco" },
  { countryIso2: "USA", stateCode: "NY", name: "New York City" },
  { countryIso2: "GBR", stateCode: "ENG", name: "London" },
  { countryIso2: "GBR", stateCode: "ENG", name: "Manchester" },
  { countryIso2: "GBR", stateCode: "SCT", name: "Edinburgh" },
  { countryIso2: "DEU", stateCode: "BE", name: "Berlin" },
  { countryIso2: "DEU", stateCode: "BY", name: "Munich" },
];
